### ISSUE TITLE
Instlaling @react-hookz/web@1.25.0 (latest currently)

### ISSUE THREAD

**Issue by TheMeteoRain** [react-hookz/web#102]
Hi, just dropping by to report this. 

### What is the current behavior?

Cannot find module '@react-hookz/web' or its corresponding type declarations.

### Steps to Reproduce

yarn add @react-hookz/web@1.25.0
or (since it's the latest currently)
yarn add @react-hookz/web

### Environment Details

- _`@react-hookz/web` version:_  1.25.0
- _`react` version:_  17.0.1
- _`react-dom` version:_  17.0.1
- _`typescript` version:_ 4.2.3
- _Did this work in previous versions?_ Yes, on 1.24.0

**Comment by xobotyi** [comment]
Maybe network issues?
```shell
PS xxxx\frontend> yarn add @react-hookz/web
yarn add v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > connected-react-router@6.9.1" has unmet peer dependency "history@^4.7.2".
warning " > optimize-css-assets-webpack-plugin@6.0.0" has incorrect peer dependency "webpack@^4.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ @react-hookz/web@1.25.0
info All dependencies
└─ @react-hookz/web@1.25.0
Done in 9.68s.
```

**Comment by xobotyi** [comment]
Oof i see now. somewhat bundle is corrupted =\

**Comment by xobotyi** [comment]
@TheMeteoRain sorry for inconvinience, my bad.
Missconfig happent, all add some distribution bundle tests to avoid this in future.

**Comment by TheMeteoRain** [comment]
Yeah, no problem. I just switched to older version and continued with my life. I just wanted to inform you about this. 😛
